---

---

<center>  <h3> Fayruz Kibria Feb 2022 </h2> </center>

---

#### Imporing the rawdata sheet (sheet 3) from the library.


```{r}

# Imporing the rawdata sheet (sheet 3) from the library

library(readxl)
library(httr)
#packageVersion("readxl")

url<-'https://archive.ics.uci.edu/ml/machine-learning-databases/00193/CTG.xls'
GET(url, write_disk(tf <- tempfile(fileext = ".xls")))


```

```{r}
# read raw data file in as dataframe

rawdata <- read_excel(tf, 3L)
str(rawdata)
head(rawdata)
tail(rawdata)
```




#### 

```{r}
# dropping incomplete cases, and irrelevant columns after examining head and tail of data

library(tidyr)

rawdata[!complete.cases(rawdata),]

df1<-rawdata %>% drop_na()

df1<- subset (df1, select = -c(FileName,Date,SegFile))
head(df1)
tail(df1)
str (df1)

```
#### 

```{r}
# assigning col names, checking for missing data, and data description

library(psych)


names <- c('Tendency', 'A',	'B',	'C',	'D',	'E',	'AD',	'DE',	'LD',	'FS',	'SUSP', 'CLASS', 'NSP')
df1[,names] <- lapply(df1[,names] , factor)

names <- c('AC',	'FM',	'UC',		'DL',	'DS',	'DP',	'DR', 'Nmax', 'Nzeros')
df1[,names] <- lapply(df1[,names] , as.integer)


cat("There are", sum(is.na(df1)), "missing data in the dataset.\n\n")



describe(df1)

```
```{r}
# deescription of categorical variables

library(SmartEDA)
#ExpCTable(df1,Target=NULL,clim=5,nlim=15,round=2,bin=NULL,per=F)
ExpCustomStat(df1,Cvar=c("Tendency","A","B","C","D","E","AD","DE","LD","FS","SUSP","CLASS", "NSP"),gpby=FALSE)
```

```{r}
# plotting all raw variable histogram

library(ggplot2)
library(gridExtra)

theme_set(
  theme_bw() +
    theme(legend.title=element_blank())+
    theme(legend.position = "top")
  )

temp<-df1

# b e
p=list()
namess<-c('b','e')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#LBE	LB	
p=list()
namess<-c('LBE','LB')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#AC	FM	UC	
p=list()
namess<-c('AC',	'FM',	'UC')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

#	DL	DS	DP	DR
p=list()
namess<-c(	'DL',	'DS',	'DP',	'DR')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#ASTV	MSTV	ALTV	MLTV	
p=list()
namess<-c('ASTV',	'MSTV',	'ALTV',	'MLTV')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

# Mode	Mean	Median	Variance Tendency
p=list()
namess<-c('Mode',	'Mean',	'Median',	'Variance','Tendency')
for (i in 1:length(namess)){
  if(i < length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
  }else{
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
  }
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

# Width	Min	Max		Nmax	Nzeros 
p=list()
namess<-c('Width',	'Min',	'Max','Nmax',	'Nzeros' )
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

#A	B	C	D	
p=list()
namess<-c('A',	'B',	'C',	'D')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#	E	AD	DE	LD
p=list()
namess<-c('E',	'AD',	'DE',	'LD')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#	FS	SUSP
p=list()
namess<-c('FS',	'SUSP')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")



# CLASS	NSP
p=list()
namess<-c( 'CLASS' ,	'NSP')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

```

```{r}
# checking the variance of the DR column

variances<-apply(df1, 2, var)
variances[which(variances<=0.0025)]


```

```{r}

# checking if there are exact duplicate columns in the dataset

dup <- ifelse(df1$LBE > df1$LB, 1,ifelse(df1$LBE < df1$LB, 1, 0))
paste0("There are ",sum(dup)," items that are different in the LB anf LBE columns.")


```


```{r}
# dropping the variable LBE because it is exact copy of the LB variable

df2<- subset (df1, select = -c(DR, LBE))
str(df2)

```

```{r}
# calculating nPoints the length of record length variable from end and start instance numbers
# normalizing the recording length sensitive variables, adding them to the data set and dropping original cols

library(dplyr)

df3 <- df2 %>% mutate(nPoints = e - b)

df3 <- df3 %>% mutate(nAC = AC/nPoints)
df3 <- df3 %>% mutate(nFM = FM/nPoints)
df3 <- df3 %>% mutate(nUC = UC/nPoints)
df3 <- df3 %>% mutate(nDL = DL/nPoints)
df3 <- df3 %>% mutate(nDS = DS/nPoints)
df3 <- df3 %>% mutate(nDP = DP/nPoints)

df4 <- subset (df3, select = -c(b,	e,	AC,	FM,	UC,	DL,	DS,	DP))#, A, B, C, D, E, AD, DE, LD, FS, SUSP))

str(df4)

```



```{r}
# re arranging the data set to have all the categorical variables grouped at the end columns

library(tidyverse)


df5<-cbind(df4 %>% select(where(is.numeric)) ,df4 %>% select(where(is.factor)) )

str(df5)
describe(df5)


```



```{r}
# plotting n points and recording-length-normalized data

theme_set(
  theme_bw() +
    theme(legend.title=element_blank())+
    theme(legend.position = "top")
  )

temp<-df5

# nPoints
p=list()
namess<-c('nPoints')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#AC	FM	UC	DL	DS	DP	
#pqq=list()
#namess<-c('AC',	'FM',	'UC',	'DL',	'DS',	'DP')
#for (i in 1:length(namess)){
#  pqq[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
#  geom_bar(binwidth=1)
#}
#grid.arrange(grobs=pqq,ncol=3, nrow=2)

# nAC	nFM	nUC	nDL	nDS	nDP
p=list()
namess<-c('nAC',	'nFM',	'nUC',	'nDL',	'nDS',	'nDP')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

```

```{r}
# min max normalizing the data, where columns are numerical

min_max_norm <- function(x) {
    (x - min(x)) / (max(x) - min(x))
  }

df6 <- as.data.frame(sapply(df5 %>% select(where(is.numeric)), min_max_norm))
df7 <- cbind(df6, df5 %>% select(where(is.factor)))

describeBy(df7, group=df7$NSP)
str(df7)



```


```{r}
# plotting min max normalized data

theme_set(
  theme_bw() +
    theme(legend.title=element_blank())+
    theme(legend.position = "top")
  )

temp<-df7

# nPoints
p=list()
namess<-c('nPoints')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#	LB	
p=list()
namess<-c('LB')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#nAC	nFM	nUC	
p=list()
namess<-c('nAC',	'nFM',	'nUC')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

#	nDL	nDS	nDP
p=list()
namess<-c(	'nDL',	'nDS',	'nDP')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

#ASTV	MSTV	ALTV	MLTV	
p=list()
namess<-c('ASTV',	'MSTV',	'ALTV',	'MLTV')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

# Mode	Mean	Median	Variance Tendency
p=list()
namess<-c('Mode',	'Mean',	'Median',	'Variance','Tendency')
for (i in 1:length(namess)){
  if(i < length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
  }else{
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
  }
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

# Width	Min	Max		Nmax	Nzeros 
p=list()
namess<-c('Width',	'Min',	'Max','Nmax',	'Nzeros' )
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_histogram(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=3, nrow=2, top = "Variable histogram with NSP Classes")

#A	B	C	D	
p=list()
namess<-c('A',	'B',	'C',	'D')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#	E	AD	DE	LD
p=list()
namess<-c('E',	'AD',	'DE',	'LD')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

#	FS	SUSP
p=list()
namess<-c('FS',	'SUSP')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")



# CLASS	NSP
p=list()
namess<-c( 'CLASS' ,	'NSP')
for (i in 1:length(namess)){
  p[[i]] <- ggplot(temp, aes_string(x = namess[i])) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))
}
grid.arrange(grobs=p,ncol=2, nrow=2, top = "Variable histogram with NSP Classes")

```

#### Exploring the correlation between the attributes other than class attribute

```{r}
# correlation plot of all the min max normalized numerical variables

library(corrplot)


col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(round(cor(select_if(df7, is.numeric)),1), method="color", col=col(200),  
         type="lower", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=90, number.cex= .6,#Text label color and rotation
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )

```

###

```{r}

# kruskal test on the min max normalized dataset

#for(i in names(df7[1:23])){  
#  kwt<-kruskal.test(formula(paste(i, "~ NSP")), data = df7)
#  print(kwt)
#}


library(broom)
kwt_df <- df7 %>% gather(key, value, -NSP) %>% 
       group_by(key) %>% 
       do(tidy(kruskal.test(x= .$value, g = .$NSP)))
#kwt_df #df5
kwt_df[with(kwt_df, order(p.value, statistic)), ] # printing most discerning variables

```
```{r}

# kruskal test on the min max normalized dataset

kwt_df[with(kwt_df, order(-p.value, statistic)), ]# reading the least discerning variables

```

#### Dividing the dataset to training and test sets. 

```{r}
# dropping nPoints because it is not significant factor in differentiating NSP

df8<-subset(df7, select=-c(nPoints))
str(df8)

```
###


```{r}
#class imbalance analysis for the whole dataset

C<-3

Tdata<-length(df8$NSP)

n1<-length(which(df8$NSP=="1"))
n2<-length(which(df8$NSP=="2"))
n3<-length(which(df8$NSP=="3"))

imbalanceStat<-abs(((1/C)-(n1/Tdata)))+abs(((1/C)-(n2/Tdata)))+abs(((1/C)-(n3/Tdata)))

cat("Class 1: ",round(n1*100/Tdata,0),"%\n")
cat("Class 2: ",round(n2*100/Tdata,0),"%\n")
cat("Class 3: ",round(n3*100/Tdata,0),"%\n\n")
cat("Imbalance: ",round(imbalanceStat,2))
```

```{r}

# writing csv file to disk for importing to python code

write.csv(df8,"df8.csv", row.names = FALSE)

```



```{r}

# importing the python train test split for plotting

train_pthn <- read.csv(file = 'X_y_train_combined.csv', )
test_pthn <- read.csv(file = 'X_y_test_combined.csv', )

names <- c('Tendency', 'A',	'B',	'C',	'D',	'E',	'AD',	'DE',	'LD',	'FS',	'SUSP', 'CLASS', 'NSP')
train_pthn[,names] <- lapply(train_pthn[,names] , factor)
test_pthn[,names] <- lapply(test_pthn[,names] , factor)

head(test_pthn)
```
```{r}
library(ggplot2)
library(gridExtra)
 theme_set(
   theme_bw() +
     theme(legend.title=element_blank())+
     theme(legend.position = "top")
   )

p<-list()
p[[1]] <- ggplot(train_pthn, aes(x=NSP)) + 
    geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))+
  geom_text(stat='count', aes(label=..count..), vjust=1.25)+
  ggtitle("Train Set NSP Count")+
  theme(plot.title = element_text(hjust = 0.5))
p[[2]] <- ggplot(test_pthn, aes(x=NSP)) + 
  geom_bar(aes(fill=factor(NSP, levels=c("3", "2", "1"))))+
  geom_text(stat='count', aes(label=..count..), vjust=1.25)+
  ggtitle("Test Set NSP Count")+
  theme(plot.title = element_text(hjust = 0.5))
grid.arrange(grobs=p,ncol=2, nrow=1)


```



